/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Eleccion;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Stephannie
 */
public class FRM_Eleccion extends javax.swing.JFrame {

    Controlador_FRM_Eleccion controladorEleccion;
    /**
     * Creates new form FRM_Eleccion
     */
    public FRM_Eleccion(FRM_MenuPrincipal frm_MenuPrincipal) {
        initComponents();
        setLocation(450,300);
               setVisible(true);
               controladorEleccion=new Controlador_FRM_Eleccion(this,frm_MenuPrincipal);
               agregarEventos(controladorEleccion);
    }
    
    public void agregarEventos(Controlador_FRM_Eleccion controladorEleccion){
        this.controladorEleccion=controladorEleccion;
        this.btn_Confirmar.addActionListener(controladorEleccion);
    }
    
    public boolean devolverEleccionArchivos(){
        boolean archivos=false;
       if(r_btn_Archivos.isSelected()==true){
           System.out.println("Archivos");
           archivos=true;
       }
      
       return archivos;
    }
    
    public boolean devolverEleccionBD(){
        boolean bd=false;
        if(r_btn_BD.isSelected()==true){
            System.out.println("BD");
            bd=true;
        }
        return bd;
    }
    
        public boolean devolverEleccionXML(){
            boolean xml=false;
        if(r_btn_Xml.isSelected()==true){
            System.out.println("XML");
            xml=true;
        }
        return xml;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEleccion = new javax.swing.ButtonGroup();
        r_btn_Archivos = new javax.swing.JRadioButton();
        r_btn_BD = new javax.swing.JRadioButton();
        r_btn_Xml = new javax.swing.JRadioButton();
        jl_mensaje = new javax.swing.JLabel();
        btn_Confirmar = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grupoEleccion.add(r_btn_Archivos);
        r_btn_Archivos.setText("Archivos Planos");
        r_btn_Archivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grupoEleccion.add(r_btn_BD);
        r_btn_BD.setText("Bases de Datos");
        r_btn_BD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grupoEleccion.add(r_btn_Xml);
        r_btn_Xml.setText("XML");
        r_btn_Xml.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jl_mensaje.setText("Elija la forma en la que desea guardar sus datos:");

        btn_Confirmar.setText("Confirmar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_btn_BD)
                            .addComponent(r_btn_Archivos)
                            .addComponent(jl_mensaje))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_btn_Xml)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Confirmar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jl_mensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_btn_Archivos)
                        .addGap(18, 18, 18)
                        .addComponent(r_btn_BD)
                        .addGap(18, 18, 18)
                        .addComponent(r_btn_Xml))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Confirmar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.ButtonGroup grupoEleccion;
    private javax.swing.JLabel jl_mensaje;
    private javax.swing.JRadioButton r_btn_Archivos;
    private javax.swing.JRadioButton r_btn_BD;
    private javax.swing.JRadioButton r_btn_Xml;
    // End of variables declaration//GEN-END:variables
}
