/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Modelo.ArchivoUsuario;
/**
 *
 * @author Stephannie
 */
public class FRM_MantenimientoUsuarios extends javax.swing.JFrame {
public Controlador_FRM_MantenimientoUsuarios controlador_FRM_MantenimientoUsuarios;
String fuente="";
ArchivoUsuario archivoUsuario;
    /**
     * Creates new form FRM_MantenimientoUsuarios
     */
    public FRM_MantenimientoUsuarios() {
        initComponents();
        controlador_FRM_MantenimientoUsuarios=new Controlador_FRM_MantenimientoUsuarios(this);
        gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoUsuarios);
        archivoUsuario=new ArchivoUsuario();
        estadoInicial();
    }
    public void estadoInicial()
    {
        gUI_Botones1.estadoInicial();
        gUI_InformacionUsuarios1.estadoInicial();
    }
    public void resetearInterfaz()
    {
        gUI_InformacionUsuarios1.resetearInterfaz();
    }
    public void habilitarAgregar()
    {
      gUI_Botones1.habilitarAgregar();
      gUI_InformacionUsuarios1.habilitarAgregar();
    }
    public void habilitarOpciones()
    {
     gUI_Botones1.habilitarOpciones();
     gUI_InformacionUsuarios1.habilitarOpciones();
    }
     public void establecerFuente(String eleccion){
        controlador_FRM_MantenimientoUsuarios.establecerFuente(eleccion);
    }
    
    public String devolverNombreDeUsuario(){
        return gUI_InformacionUsuarios1.devolverNombreDeUsuario();
    }
    
    public void devolverConstraseña(){
        this.devolverConstraseña();
    }
    

    public String fuente()
    {
     System.out.println("1"+fuente);
     return fuente;
        
    }
   public String[] devolverInformacion()
    {
      return gUI_InformacionUsuarios1.devolverInformacion();
    }
   public String devolverNombreUsuario()
   {
       return gUI_InformacionUsuarios1.devolverNombreDeUsuario();
   }
   public void  mostrarInformacion(String arreglo[])
   {
       this.gUI_InformacionUsuarios1.mostrarInformacion(arreglo);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionUsuarios1 = new Vista.GUI_InformacionUsuarios();
        gUI_Botones1 = new Vista.GUI_Botones();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gUI_InformacionUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      archivoUsuario.devolverInformacionDeUsuarios();
      archivoUsuario.crearArchivoEUsuario();
      controlador_FRM_MantenimientoUsuarios.guardarArchivo();// TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionUsuarios gUI_InformacionUsuarios1;
    // End of variables declaration//GEN-END:variables
}
